### ISSUE TITLE
dft.hpp代码src = dst过不了编译

### ISSUE THREAD

**Issue by EvePhil** [fengbingchun/OpenCV_Test#1]
很棒！但是昨天我在vs2017编译时保了以下错误：
C2679	二进制“=”: 没有找到接受“fbc::Mat_<float,2>”类型的右操作数的运算符(或没有可接受的转换)
似乎是vs的标准不允许chs不同的模板类之间的直接赋值，目前为止没有在2013上测试过，所以这可能是140+的限制？有没有什么办法避开这个问题呢？

**Comment by fengbingchun** [comment]
@EvePhil 还没有在vs2017上测试过，在vs2013和gcc 4.9上都是正常的。你有作任何修改吗，还是直接clone后使用vs2017编译就直接报这个错误？可否更详细的藐视下，后面有时间，我可以在vs2017上进一步测试下，谢谢

**Comment by fengbingchun** [comment]
@EvePhil  我在windows10 vs community 2017上重新编译了fbc_cv和OpenCV_Test两个工程，在debug和release下均正常，没有出现你说的error，vs community 2017版本号为15.8.9
