### ISSUE TITLE
在Ubuntu上编译的无法读取图像

### ISSUE THREAD

**Issue by aimuch** [fengbingchun/OpenCV_Test#2]
在Ubuntu上编译的时候遇到以下几个问题：   
### 2. 无法读取图像的错误
原因是`test_opencv_funset.cpp`的18行，在linux平台下读取了
```cpp
matSrc = cv::imread("lena.jpg");
```
should:
```cpp
matSrc = cv::imread("test_images/lena.png");
```

**Comment by fengbingchun** [comment]
@aimuch  谢谢指正，两个问题均已修正

**Comment by aimuch** [comment]
@fengbingchun 太客气了，在测试`warpPerspective`这个函数的时候遇到以下错误了吗？
```bash
demo/OpenCV_Test/test_warpPerspective.cpp:121: int test_warpPerspective_uchar(): Assertion `p[x] == p_[x]' failed.
[1]    26575 abort (core dumped)  ./OpenCV_Test
```

**Comment by fengbingchun** [comment]
@aimuch 我在windows和linux下都单独执行test_warpPerspective_uchar这个测试函数，都正常，windows使用的是vs2013, ubuntu 14.04上gcc是4.9.4

**Comment by aimuch** [comment]
@fengbingchun OK，我在试一下

**Comment by fengbingchun** [comment]
@aimuch fbc::warpAffine和cv::warpAffine有作对比，见test_warpAffine.cpp文件

**Comment by aimuch** [comment]
> @aimuch fbc::warpAffine和cv::warpAffine有作对比，见test_warpAffine.cpp文件
[这里判断的是warp_mat和warp_mat_哦，](https://github.com/fengbingchun/OpenCV_Test/blob/8f2d8343868f0bd8efb1e22bf710f3de90dd03b3/demo/OpenCV_Test/test_warpAffine.cpp#L211)，并没有对比fbc生成的`warp_dst`和opencv生成的`warp_dst_`图像。

**Comment by fengbingchun** [comment]
@aimuch 之前的code确实没有对两边warpAffine的结果进行比对，已修复，两边产生的结果一致
