### ISSUE TITLE
为什么插值算法的nearest neighbour这么复杂 对比之前的

### ISSUE THREAD

**Issue by ggcleyang** [fengbingchun/OpenCV_Test#3]
不好意思，打扰了
https://github.com/fengbingchun/OpenCV_Test/blob/master/src/fbc_cv/include/resize.hpp
line 844-932 里面有不同case
简单的方法：https://blog.csdn.net/fengbingchun/article/details/17335477  这里的resizeNN很简单
 这两种方法 有什么不同？

**Comment by fengbingchun** [comment]
@ggcleyang (1). blog中的只支持bgr或rgb三通道图像，而github中的支持范围更广，可是各种类型的；(2). 它们基本都是按照公式来实现的，结果应该是一致的，只是github中会同时并行处理多个像素，速度更快。

**Comment by ggcleyang** [comment]
学习了  感谢回复
